### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by JamersonAguiarOSF** [gpbl/react-day-picker#2524]
### Discussed in https://github.com/gpbl/react-day-picker/discussions/2521

<div type='discussions-op-text'>

<sup>Originally posted by **JamersonAguiarOSF** October  7, 2024</sup>
Using react-day-picker 9.1.3 in a monorepo project (lerna), some tests started failing with the following error

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    C:\dev\project\node_modules\react-day-picker\node_modules\date-fns\addDays.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { constructFrom } from "./constructFrom.js";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { DayPicker, DayPickerProps } from 'react-day-picker';
        | ^
      2 |
      3 | import 'react-day-picker/style.css';
      4 | import './Calendar.scss';

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../node_modules/react-day-picker/src/lib/dateLib.ts:5:1)
      at Object.<anonymous> (../../node_modules/react-day-picker/src/helpers/getDateLib.ts:1:1)
      at Object.<anonymous> (../../node_modules/react-day-picker/src/DayPicker.tsx:14:1)
      at Object.<anonymous> (../../node_modules/react-day-picker/src/index.ts:1:1)
      at Object.<anonymous> (../../components/analyticsByPublishDateApp/components/calendar/Calendar.tsx:1:1)
      at Object.<anonymous> (../../components/analyticsByPublishDateApp/containers/analyticsByPublishDate/components/headerAnalyticsByPublishDate/components/DropdownMetricsDateRange.tsx:6:1)
      at Object.<anonymous> (../../components/analyticsByPublishDateApp/containers/analyticsByPublishDate/components/headerAnalyticsByPublishDate/HeaderAnalyticsByPublishDate.tsx:4:1)  
      at Object.<anonymous> (../../components/analyticsByPublishDateApp/containers/analyticsByPublishDate/AnalyticsByPublishDate.tsx:3:1)
      at Object.<anonymous> (../../components/analyticsByPublishDateApp/AnalyticsByPublishDateApp.tsx:2:1)</div>

**Comment by gpbl** [comment]
dup of https://github.com/gpbl/react-day-picker/discussions/2521
