### ISSUE TITLE
Few failing tests

### ISSUE THREAD

**Issue by adambbecker** [gpbl/react-day-picker#32]
Noticed a few tests are currently failing (*at least for me*):

![screen shot 2015-07-25 at 10 53 42 am](https://cloud.githubusercontent.com/assets/1427136/8890005/b737b778-32bd-11e5-806c-c04f07372a32.png)

**Daypicker**
* [ ] does not render outside days
* [ ] renders outside days when required
* [ ] adds an `outside` modifier to outside days
* [ ] changes the month when calling showMonth

![screen shot 2015-07-25 at 10 53 56 am](https://cloud.githubusercontent.com/assets/1427136/8890008/bb6bba42-32bd-11e5-9b2f-c2827f9ad98f.png)

**Utils**
* getWeekArray
  * [ ] works with a month starting on sunday (en)
* isDayOutsideMonth
  * [ ] detects days outside a month
  * [ ] does detect days inside a month

**Comment by gpbl** [comment]
Weird! Could you please check the result of `npm list -depth=0` and `node -v`?

```
$ npm list -depth=0
react-day-picker@1.0.2 ~/Development/react-day-picker
├── babel@5.8.5
├── babel-core@5.8.5
├── babel-eslint@3.1.27
├── chai@3.2.0
├── classlist-polyfill@1.0.2
├── coveralls@2.11.3
├── eslint@0.23.0
├── eslint-plugin-react@2.7.1
├── istanbul@0.3.17
├── jsdom@3.1.2
├── mocha@2.2.5
├── moment@2.10.3
├── react@0.13.3
├── react-tap-event-plugin@0.1.7
├── sinon@1.15.4
└── sinon-chai@2.8.0

$ node -v
v0.12.6
```

**Comment by adambbecker** [comment]
Sure thing

```
$ npm list -depth=0
react-day-picker@1.0.2 /Users/adambecker/Sites/OpenSource/react-day-picker
├── babel@5.8.3
├── babel-core@5.8.3
├── babel-eslint@3.1.26
├── chai@3.2.0
├── classlist-polyfill@1.0.2
├── coveralls@2.11.3
├── eslint@0.23.0
├── eslint-plugin-react@2.7.1
├── istanbul@0.3.17
├── jsdom@3.1.2
├── mocha@2.2.5
├── moment@2.10.3
├── react@0.13.3
├── react-tap-event-plugin@0.1.7
├── sinon@1.15.4
└── sinon-chai@2.8.0

$ node -v
v0.12.7
```

**Comment by gpbl** [comment]
uhm I can't understand why. After the test it should report the errors, e.g.

```
  1) DayPicker renders the weekday names:
     AssertionError: expected [ Array(7) ] to have a length of 71 but got 7
      at Context.<anonymous> (tests/DayPicker.js:177:31)
```

could you please post the whole test log? are you on osx or linux? what is your default language?

**Comment by adambbecker** [comment]
Yeah, definitely a little crazy, most likely a symptom of my system.

##### Test Log
```
> react-day-picker@1.0.2 test /Users/adambecker/Sites/OpenSource/react-day-picker
> mocha tests/* --compilers js:babel/register --recursive --reporter spec



  DayPicker
    ✓ has the default props properly set
    ✓ has a DayPicker class (with locale)
    ✓ has a role attribute
    ✓ has a tabIndex attribute
    ✓ does not contain a interactionEnabled modifier
    ✓ uses the `className` prop
    ✓ uses the `style` prop
    ✓ renders the number of months as specified by initialMonth (76ms)
    ✓ renders a caption for each month (73ms)
    ✓ renders the navigation buttons
    ✓ does not render the navigation buttons
    ✓ renders the weekday names
    ✓ renders the weeks elements in a month
    ✓ renders the days element in a month
    1) does not render outside days
    2) renders outside days when required
    3) adds an `outside` modifier to outside days
    ✓ adds a `today` modifier to today date
    ✓ adds custom modifiers
    ✓ changes the month when calling showNextMonth (78ms)
    ✓ changes the month when calling showPreviousMonth (59ms)
    4) changes the month when calling showMonth
    ✓ displays a modified state upon changing initialMonth prop
    ✓ displays the same state when changing another prop
    ✓ updates its state when clicking to the next month button
    ✓ updates its state when clicking to the previous month button
    ✓ calls onMonthChange
    ✓ calls event handlers on caption
    ✓ calls event handlers on a day cell
    ✓ calls touch-tap event handler on a day cell
    ✓ does not call event handlers on a day cell without event prop
    ✓ does not call mouse events on disabled outside days
    ✓ changes the month when tapping on enabled outside days
    ✓ changes the month when clicking on enabled outside days
    ✓ calls onDayClick when enter key is pressed on a day cell
    ✓ calls onDayClick when space key is pressed on a day cell
    ✓ calls onDayTouchTap when enter key is pressed on a day cell
    ✓ calls showPreviousMonth when left key is pressed over the root node (59ms)
    ✓ does not call showPreviousMonth when another key is pressed
    ✓ calls showNextMonth when right key is pressed (51ms)
    ✓ does not call showNextMonth if another key is pressed
    ✓ calls focusPreviousDay when left key is pressed (47ms)
    ✓ calls focusNextDay when right key is pressed
    Keyboard navigation
      ✓ focuses the previous day of the same month
      ✓ focuses the last day of the previous week
      ✓ focuses the last day of the previous month
      ✓ focuses the next day of the same month
      ✓ focuses the first day of the next week
      ✓ focuses the first day of the next month

  Utils
    clone
      ✓ should clone a date
    addMonths
      ✓ adds a month
      ✓ should remove two months
    startOfMonth
      ✓ should set a date as start of its month
    getFirstDayOfMonth
      ✓ get the first day of the month
    getDaysInMonth
      ✓ get the correct number of days
      ✓ get the correct number of days in a leap month
    getWeekArray
      5) works with a month starting on sunday (en)
      ✓ adds days from the previous month to the first week (en)
      ✓ adds days from the next month to the last week (en)
      ✓ adds days from the next month to the last week (it)
      ✓ returns 7 days per week when starting day is sunday
      ✓ returns 7 days per week when starting day is monday
      ✓ returns 7 days per week when starting day is saturday
    getModifiersForDay
      ✓ returns an array of modifiers
      ✓ works without passing modifiers
    isDayOutsideMonth
      6) detects days outside a month
      7) does detect days inside a month
    isSameDay
      ✓ returns true if two days differ only by time
      ✓ returns false for different days
    formatMonthTitle
      ✓ returns month and day as string
    formatWeekdayShort
      ✓ returns the short day name as string
    formatWeekdayLong
      ✓ returns the long day name as string
    getFirstDayOfWeek
      ✓ returns sunday

  LocaleUtils
    formatMonthTitle
      ✓ should return month and day as string
    formatWeekdayShort
      ✓ should return the short day name as string
    formatWeekdayLong
      ✓ should return the long day name as string
    getFirstDayOfWeek
      ✓ should return monday for it locale
      ✓ should return sunday for en locale


  71 passing (4s)
  7 failing

  1) DayPicker does not render outside days:

      AssertionError: expected '1' to equal ''
      + expected - actual

      -1
      
      at Context.<anonymous> (tests/DayPicker.js:210:53)

  2) DayPicker renders outside days when required:

      AssertionError: expected '31' to equal '28'
      + expected - actual

      -31
      +28
      
      at Context.<anonymous> (tests/DayPicker.js:221:53)

  3) DayPicker adds an `outside` modifier to outside days:

      AssertionError: expected '31' to equal '28'
      + expected - actual

      -31
      +28
      
      at Context.<anonymous> (tests/DayPicker.js:233:53)

  4) DayPicker changes the month when calling showMonth:

      AssertionError: expected 7 to equal 8
      + expected - actual

      -7
      +8
      
      at Context.<anonymous> (tests/DayPicker.js:325:58)

  5) Utils getWeekArray works with a month starting on sunday (en):

      AssertionError: expected 27 to equal 1
      + expected - actual

      -27
      +1
      
      at Context.<anonymous> (tests/Utils.js:74:40)

  6) Utils isDayOutsideMonth detects days outside a month:
     AssertionError: expected false to be true
  

  7) Utils isDayOutsideMonth does detect days inside a month:
     AssertionError: expected true to be false
```

##### NPM Debug

I did notice a `npm-debug.log` after running the test script, here are the contents:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@2.13.2
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'pretest', 'test', 'posttest' ]
6 info pretest react-day-picker@1.0.2
7 info test react-day-picker@1.0.2
8 verbose unsafe-perm in lifecycle true
9 info react-day-picker@1.0.2 Failed to exec test script
10 verbose stack Error: react-day-picker@1.0.2 test: `mocha tests/* --compilers js:babel/register --recursive --reporter spec`
10 verbose stack Exit status 7
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid react-day-picker@1.0.2
12 verbose cwd /Users/adambecker/Sites/OpenSource/react-day-picker
13 error Darwin 14.4.0
14 error argv "node" "/usr/local/bin/npm" "run" "test"
15 error node v0.12.7
16 error npm  v2.13.2
17 error code ELIFECYCLE
18 error react-day-picker@1.0.2 test: `mocha tests/* --compilers js:babel/register --recursive --reporter spec`
18 error Exit status 7
19 error Failed at the react-day-picker@1.0.2 test script 'mocha tests/* --compilers js:babel/register --recursive --reporter spec'.
19 error This is most likely a problem with the react-day-picker package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     mocha tests/* --compilers js:babel/register --recursive --reporter spec
19 error You can get their info via:
19 error     npm owner ls react-day-picker
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

---

**System** | OSX
**Default Language** | English

**Comment by gpbl** [comment]
English... US? UK? AU? :-)

Ah! maybe i got it! If you run this

```
$ node
> new Date("2015-07-01")
Wed Jul 01 2015 02:00:00 GMT+0200 (CEST)
```

you should get january - do you?

**Comment by adambbecker** [comment]
> English... US? UK? AU? :-)

Haha, always forget about that: **US** *'Merican* :-)

```
$ node
> new Date("2015-07-01")
Tue Jun 30 2015 20:00:00 GMT-0400 (EDT)
```

I get June... which is weird.

**Comment by gpbl** [comment]
lol yes it's because the timezone... i find always it confusing... you say "i want 7th of july at midnight" which is the 30th of june at 8PM in EDT. which is crazy because i need the 7th of july in *your timezone*. I think that form of passing a date is wrong. So I expect that

```
$node
new Date(2015, 07, 01)
```

returns the 1st of august also *for you*. 

Could you check, if you don't mind?

**Comment by adambbecker** [comment]
lol, that is super weird.

Confirmed that

```
$ node
> new Date(2015, 07, 01)
Sat Aug 01 2015 00:00:00 GMT-0400 (EDT)
```

Returns August 1st.

**Comment by gpbl** [comment]
Yeah definitely I should not pass a string to `new Date()`, it get converted then to the machine's timezone. Thanks for reporting it! I've learnt something new :-)

**Comment by adambbecker** [comment]
> should not pass a string to new Date(), it will be converted to the machine's timezone.

Wow, yeah that is good to know. No problem, learned something new myself :-)
